DROP TABLE IF EXISTS `countries`;
CREATE TABLE `countries` (
  `countries_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`countries_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `countries` (`code`, `name`, `full_name`) VALUES
('VN', 'Việt Nam', 'Cộng hòa Xã hội Chủ nghĩa Việt Nam'),
('US', 'Hoa Kỳ', 'Hợp chủng quốc Hoa Kỳ'),
('JP', 'Nhật Bản', 'Nhật Bản'),
('KR', 'Hàn Quốc', 'Đại Hàn Dân Quốc'),
('CN', 'Trung Quốc', 'Cộng hòa Nhân dân Trung Hoa'),
('FR', 'Pháp', 'Cộng hòa Pháp'),
('DE', 'Đức', 'Cộng hòa Liên bang Đức'),
('GB', 'Anh', 'Vương quốc Liên hiệp Anh và Bắc Ireland'),
('RU', 'Nga', 'Liên bang Nga'),
('CA', 'Canada', 'Canada'),
('AU', 'Úc', 'Liên bang Úc'),
('TH', 'Thái Lan', 'Vương quốc Thái Lan'),
('SG', 'Singapore', 'Cộng hòa Singapore'),
('MY', 'Malaysia', 'Malaysia'),
('ID', 'Indonesia', 'Cộng hòa Indonesia'),
('PH', 'Philippines', 'Cộng hòa Philippines'),
('IN', 'Ấn Độ', 'Cộng hòa Ấn Độ'),
('KH', 'Campuchia', 'Vương quốc Campuchia'),
('LA', 'Lào', 'Cộng hòa Dân chủ Nhân dân Lào'),
('MM', 'Myanmar', 'Cộng hòa Liên bang Myanmar'),
('BR', 'Brazil', 'Cộng hòa Liên bang Brazil'),
('MX', 'Mexico', 'Hợp chủng quốc Mexico'),
('AR', 'Argentina', 'Cộng hòa Argentina'),
('ZA', 'Nam Phi', 'Cộng hòa Nam Phi'),
('NZ', 'New Zealand', 'New Zealand'),
('CH', 'Thụy Sĩ', 'Liên bang Thụy Sĩ'),
('SE', 'Thụy Điển', 'Vương quốc Thụy Điển'),
('NO', 'Na Uy', 'Vương quốc Na Uy'),
('DK', 'Đan Mạch', 'Vương quốc Đan Mạch'),
('FI', 'Phần Lan', 'Cộng hòa Phần Lan'),
('IT', 'Ý', 'Cộng hòa Ý'),
('ES', 'Tây Ban Nha', 'Vương quốc Tây Ban Nha'),
('PT', 'Bồ Đào Nha', 'Cộng hòa Bồ Đào Nha'),
('PL', 'Ba Lan', 'Cộng hòa Ba Lan'),
('CZ', 'Séc', 'Cộng hòa Séc'),
('HU', 'Hungary', 'Hungary'),
('TR', 'Thổ Nhĩ Kỳ', 'Cộng hòa Thổ Nhĩ Kỳ'),
('IR', 'Iran', 'Cộng hòa Hồi giáo Iran'),
('IQ', 'Iraq', 'Cộng hòa Iraq'),
('SA', 'Ả Rập Xê Út', 'Vương quốc Ả Rập Xê Út'),
('AE', 'UAE', 'Các Tiểu vương quốc Ả Rập Thống nhất'),
('EG', 'Ai Cập', 'Cộng hòa Ả Rập Ai Cập'),
('NG', 'Nigeria', 'Cộng hòa Liên bang Nigeria'),
('KE', 'Kenya', 'Cộng hòa Kenya'),
('ET', 'Ethiopia', 'Cộng hòa Dân chủ Liên bang Ethiopia'),
('SD', 'Sudan', 'Cộng hòa Sudan'),
('PK', 'Pakistan', 'Cộng hòa Hồi giáo Pakistan'),
('BD', 'Bangladesh', 'Cộng hòa Nhân dân Bangladesh'),
('LK', 'Sri Lanka', 'Cộng hòa Dân chủ Xã hội Chủ nghĩa Sri Lanka'),
('NP', 'Nepal', 'Cộng hòa Dân chủ Liên bang Nepal'),
('BT', 'Bhutan', 'Vương quốc Bhutan'),
('MV', 'Maldives', 'Cộng hòa Maldives'),
('AF', 'Afghanistan', 'Cộng hòa Hồi giáo Afghanistan'),
('IL', 'Israel', 'Nhà nước Israel'),
('JO', 'Jordan', 'Vương quốc Jordan'),
('LB', 'Lebanon', 'Cộng hòa Liban'),
('SY', 'Syria', 'Cộng hòa Ả Rập Syria'),
('YE', 'Yemen', 'Cộng hòa Yemen'),
('OM', 'Oman', 'Vương quốc Oman'),
('QA', 'Qatar', 'Nhà nước Qatar'),
('KW', 'Kuwait', 'Nhà nước Kuwait'),
('BH', 'Bahrain', 'Vương quốc Bahrain');