DROP TABLE IF EXISTS `districts`;
CREATE TABLE `districts` (
  `districts_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `provinces_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`districts_id`),
  KEY `fk_province` (`provinces_id`),
  CONSTRAINT `fk_province_district` FOREIGN KEY (`provinces_id`) REFERENCES `provinces` (`provinces_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `districts` (`provinces_id`, `name`, `full_name`) VALUES
(1, 'Huyện 1 - Hà Nội', 'Huyện 1 - Hà Nội'),
(1, 'Huyện 2 - Hà Nội', 'Huyện 2 - Hà Nội'),
(1, 'Huyện 3 - Hà Nội', 'Huyện 3 - Hà Nội'),
(2, 'Huyện 1 - Hà Giang', 'Huyện 1 - Hà Giang'),
(2, 'Huyện 2 - Hà Giang', 'Huyện 2 - Hà Giang'),
(2, 'Huyện 3 - Hà Giang', 'Huyện 3 - Hà Giang'),
(3, 'Huyện 1 - Cao Bằng', 'Huyện 1 - Cao Bằng'),
(3, 'Huyện 2 - Cao Bằng', 'Huyện 2 - Cao Bằng'),
(3, 'Huyện 3 - Cao Bằng', 'Huyện 3 - Cao Bằng'),
(4, 'Huyện 1 - Bắc Kạn', 'Huyện 1 - Bắc Kạn'),
(4, 'Huyện 2 - Bắc Kạn', 'Huyện 2 - Bắc Kạn'),
(4, 'Huyện 3 - Bắc Kạn', 'Huyện 3 - Bắc Kạn'),
(5, 'Huyện 1 - Tuyên Quang', 'Huyện 1 - Tuyên Quang'),
(5, 'Huyện 2 - Tuyên Quang', 'Huyện 2 - Tuyên Quang'),
(5, 'Huyện 3 - Tuyên Quang', 'Huyện 3 - Tuyên Quang'),
(6, 'Huyện 1 - Lào Cai', 'Huyện 1 - Lào Cai'),
(6, 'Huyện 2 - Lào Cai', 'Huyện 2 - Lào Cai'),
(6, 'Huyện 3 - Lào Cai', 'Huyện 3 - Lào Cai'),
(7, 'Huyện 1 - Điện Biên', 'Huyện 1 - Điện Biên'),
(7, 'Huyện 2 - Điện Biên', 'Huyện 2 - Điện Biên'),
(7, 'Huyện 3 - Điện Biên', 'Huyện 3 - Điện Biên'),
(8, 'Huyện 1 - Lai Châu', 'Huyện 1 - Lai Châu'),
(8, 'Huyện 2 - Lai Châu', 'Huyện 2 - Lai Châu'),
(8, 'Huyện 3 - Lai Châu', 'Huyện 3 - Lai Châu'),
(9, 'Huyện 1 - Sơn La', 'Huyện 1 - Sơn La'),
(9, 'Huyện 2 - Sơn La', 'Huyện 2 - Sơn La'),
(9, 'Huyện 3 - Sơn La', 'Huyện 3 - Sơn La'),
(10, 'Huyện 1 - Yên Bái', 'Huyện 1 - Yên Bái'),
(10, 'Huyện 2 - Yên Bái', 'Huyện 2 - Yên Bái'),
(10, 'Huyện 3 - Yên Bái', 'Huyện 3 - Yên Bái'),
(11, 'Huyện 1 - Hòa Bình', 'Huyện 1 - Hòa Bình'),
(11, 'Huyện 2 - Hòa Bình', 'Huyện 2 - Hòa Bình'),
(11, 'Huyện 3 - Hòa Bình', 'Huyện 3 - Hòa Bình'),
(12, 'Huyện 1 - Thái Nguyên', 'Huyện 1 - Thái Nguyên'),
(12, 'Huyện 2 - Thái Nguyên', 'Huyện 2 - Thái Nguyên'),
(12, 'Huyện 3 - Thái Nguyên', 'Huyện 3 - Thái Nguyên'),
(13, 'Huyện 1 - Lạng Sơn', 'Huyện 1 - Lạng Sơn'),
(13, 'Huyện 2 - Lạng Sơn', 'Huyện 2 - Lạng Sơn'),
(13, 'Huyện 3 - Lạng Sơn', 'Huyện 3 - Lạng Sơn'),
(14, 'Huyện 1 - Quảng Ninh', 'Huyện 1 - Quảng Ninh'),
(14, 'Huyện 2 - Quảng Ninh', 'Huyện 2 - Quảng Ninh'),
(14, 'Huyện 3 - Quảng Ninh', 'Huyện 3 - Quảng Ninh'),
(15, 'Huyện 1 - Bắc Giang', 'Huyện 1 - Bắc Giang'),
(15, 'Huyện 2 - Bắc Giang', 'Huyện 2 - Bắc Giang'),
(15, 'Huyện 3 - Bắc Giang', 'Huyện 3 - Bắc Giang'),
(16, 'Huyện 1 - Phú Thọ', 'Huyện 1 - Phú Thọ'),
(16, 'Huyện 2 - Phú Thọ', 'Huyện 2 - Phú Thọ'),
(16, 'Huyện 3 - Phú Thọ', 'Huyện 3 - Phú Thọ'),
(17, 'Huyện 1 - Vĩnh Phúc', 'Huyện 1 - Vĩnh Phúc'),
(17, 'Huyện 2 - Vĩnh Phúc', 'Huyện 2 - Vĩnh Phúc'),
(17, 'Huyện 3 - Vĩnh Phúc', 'Huyện 3 - Vĩnh Phúc'),
(18, 'Huyện 1 - Bắc Ninh', 'Huyện 1 - Bắc Ninh'),
(18, 'Huyện 2 - Bắc Ninh', 'Huyện 2 - Bắc Ninh'),
(18, 'Huyện 3 - Bắc Ninh', 'Huyện 3 - Bắc Ninh'),
(19, 'Huyện 1 - Hải Dương', 'Huyện 1 - Hải Dương'),
(19, 'Huyện 2 - Hải Dương', 'Huyện 2 - Hải Dương'),
(19, 'Huyện 3 - Hải Dương', 'Huyện 3 - Hải Dương'),
(20, 'Huyện 1 - Hải Phòng', 'Huyện 1 - Hải Phòng'),
(20, 'Huyện 2 - Hải Phòng', 'Huyện 2 - Hải Phòng'),
(20, 'Huyện 3 - Hải Phòng', 'Huyện 3 - Hải Phòng'),
(21, 'Huyện 1 - Hưng Yên', 'Huyện 1 - Hưng Yên'),
(21, 'Huyện 2 - Hưng Yên', 'Huyện 2 - Hưng Yên'),
(21, 'Huyện 3 - Hưng Yên', 'Huyện 3 - Hưng Yên'),
(22, 'Huyện 1 - Thái Bình', 'Huyện 1 - Thái Bình'),
(22, 'Huyện 2 - Thái Bình', 'Huyện 2 - Thái Bình'),
(22, 'Huyện 3 - Thái Bình', 'Huyện 3 - Thái Bình'),
(23, 'Huyện 1 - Hà Nam', 'Huyện 1 - Hà Nam'),
(23, 'Huyện 2 - Hà Nam', 'Huyện 2 - Hà Nam'),
(23, 'Huyện 3 - Hà Nam', 'Huyện 3 - Hà Nam'),
(24, 'Huyện 1 - Nam Định', 'Huyện 1 - Nam Định'),
(24, 'Huyện 2 - Nam Định', 'Huyện 2 - Nam Định'),
(24, 'Huyện 3 - Nam Định', 'Huyện 3 - Nam Định'),
(25, 'Huyện 1 - Ninh Bình', 'Huyện 1 - Ninh Bình'),
(25, 'Huyện 2 - Ninh Bình', 'Huyện 2 - Ninh Bình'),
(25, 'Huyện 3 - Ninh Bình', 'Huyện 3 - Ninh Bình'),
(26, 'Huyện 1 - Thanh Hóa', 'Huyện 1 - Thanh Hóa'),
(26, 'Huyện 2 - Thanh Hóa', 'Huyện 2 - Thanh Hóa'),
(26, 'Huyện 3 - Thanh Hóa', 'Huyện 3 - Thanh Hóa'),
(27, 'Huyện 1 - Nghệ An', 'Huyện 1 - Nghệ An'),
(27, 'Huyện 2 - Nghệ An', 'Huyện 2 - Nghệ An'),
(27, 'Huyện 3 - Nghệ An', 'Huyện 3 - Nghệ An'),
(28, 'Huyện 1 - Hà Tĩnh', 'Huyện 1 - Hà Tĩnh'),
(28, 'Huyện 2 - Hà Tĩnh', 'Huyện 2 - Hà Tĩnh'),
(28, 'Huyện 3 - Hà Tĩnh', 'Huyện 3 - Hà Tĩnh'),
(29, 'Huyện 1 - Quảng Bình', 'Huyện 1 - Quảng Bình'),
(29, 'Huyện 2 - Quảng Bình', 'Huyện 2 - Quảng Bình'),
(29, 'Huyện 3 - Quảng Bình', 'Huyện 3 - Quảng Bình'),
(30, 'Huyện 1 - Quảng Trị', 'Huyện 1 - Quảng Trị'),
(30, 'Huyện 2 - Quảng Trị', 'Huyện 2 - Quảng Trị'),
(30, 'Huyện 3 - Quảng Trị', 'Huyện 3 - Quảng Trị'),
(31, 'Huyện 1 - Thừa Thiên Huế', 'Huyện 1 - Thừa Thiên Huế'),
(31, 'Huyện 2 - Thừa Thiên Huế', 'Huyện 2 - Thừa Thiên Huế'),
(31, 'Huyện 3 - Thừa Thiên Huế', 'Huyện 3 - Thừa Thiên Huế'),
(32, 'Huyện 1 - Đà Nẵng', 'Huyện 1 - Đà Nẵng'),
(32, 'Huyện 2 - Đà Nẵng', 'Huyện 2 - Đà Nẵng'),
(32, 'Huyện 3 - Đà Nẵng', 'Huyện 3 - Đà Nẵng'),
(33, 'Huyện 1 - Quảng Nam', 'Huyện 1 - Quảng Nam'),
(33, 'Huyện 2 - Quảng Nam', 'Huyện 2 - Quảng Nam'),
(33, 'Huyện 3 - Quảng Nam', 'Huyện 3 - Quảng Nam'),
(34, 'Huyện 1 - Quảng Ngãi', 'Huyện 1 - Quảng Ngãi'),
(34, 'Huyện 2 - Quảng Ngãi', 'Huyện 2 - Quảng Ngãi'),
(34, 'Huyện 3 - Quảng Ngãi', 'Huyện 3 - Quảng Ngãi'),
(35, 'Huyện 1 - Bình Định', 'Huyện 1 - Bình Định'),
(35, 'Huyện 2 - Bình Định', 'Huyện 2 - Bình Định'),
(35, 'Huyện 3 - Bình Định', 'Huyện 3 - Bình Định'),
(36, 'Huyện 1 - Phú Yên', 'Huyện 1 - Phú Yên'),
(36, 'Huyện 2 - Phú Yên', 'Huyện 2 - Phú Yên'),
(36, 'Huyện 3 - Phú Yên', 'Huyện 3 - Phú Yên'),
(37, 'Huyện 1 - Khánh Hòa', 'Huyện 1 - Khánh Hòa'),
(37, 'Huyện 2 - Khánh Hòa', 'Huyện 2 - Khánh Hòa'),
(37, 'Huyện 3 - Khánh Hòa', 'Huyện 3 - Khánh Hòa'),
(38, 'Huyện 1 - Ninh Thuận', 'Huyện 1 - Ninh Thuận'),
(38, 'Huyện 2 - Ninh Thuận', 'Huyện 2 - Ninh Thuận'),
(38, 'Huyện 3 - Ninh Thuận', 'Huyện 3 - Ninh Thuận'),
(39, 'Huyện 1 - Bình Thuận', 'Huyện 1 - Bình Thuận'),
(39, 'Huyện 2 - Bình Thuận', 'Huyện 2 - Bình Thuận'),
(39, 'Huyện 3 - Bình Thuận', 'Huyện 3 - Bình Thuận'),
(40, 'Huyện 1 - Kon Tum', 'Huyện 1 - Kon Tum'),
(40, 'Huyện 2 - Kon Tum', 'Huyện 2 - Kon Tum'),
(40, 'Huyện 3 - Kon Tum', 'Huyện 3 - Kon Tum'),
(41, 'Huyện 1 - Gia Lai', 'Huyện 1 - Gia Lai'),
(41, 'Huyện 2 - Gia Lai', 'Huyện 2 - Gia Lai'),
(41, 'Huyện 3 - Gia Lai', 'Huyện 3 - Gia Lai'),
(42, 'Huyện 1 - Đắk Lắk', 'Huyện 1 - Đắk Lắk'),
(42, 'Huyện 2 - Đắk Lắk', 'Huyện 2 - Đắk Lắk'),
(42, 'Huyện 3 - Đắk Lắk', 'Huyện 3 - Đắk Lắk'),
(43, 'Huyện 1 - Đắk Nông', 'Huyện 1 - Đắk Nông'),
(43, 'Huyện 2 - Đắk Nông', 'Huyện 2 - Đắk Nông'),
(43, 'Huyện 3 - Đắk Nông', 'Huyện 3 - Đắk Nông'),
(44, 'Huyện 1 - Lâm Đồng', 'Huyện 1 - Lâm Đồng'),
(44, 'Huyện 2 - Lâm Đồng', 'Huyện 2 - Lâm Đồng'),
(44, 'Huyện 3 - Lâm Đồng', 'Huyện 3 - Lâm Đồng'),
(45, 'Huyện 1 - Bình Phước', 'Huyện 1 - Bình Phước'),
(45, 'Huyện 2 - Bình Phước', 'Huyện 2 - Bình Phước'),
(45, 'Huyện 3 - Bình Phước', 'Huyện 3 - Bình Phước'),
(46, 'Huyện 1 - Tây Ninh', 'Huyện 1 - Tây Ninh'),
(46, 'Huyện 2 - Tây Ninh', 'Huyện 2 - Tây Ninh'),
(46, 'Huyện 3 - Tây Ninh', 'Huyện 3 - Tây Ninh'),
(47, 'Huyện 1 - Bình Dương', 'Huyện 1 - Bình Dương'),
(47, 'Huyện 2 - Bình Dương', 'Huyện 2 - Bình Dương'),
(47, 'Huyện 3 - Bình Dương', 'Huyện 3 - Bình Dương'),
(48, 'Huyện 1 - Đồng Nai', 'Huyện 1 - Đồng Nai'),
(48, 'Huyện 2 - Đồng Nai', 'Huyện 2 - Đồng Nai'),
(48, 'Huyện 3 - Đồng Nai', 'Huyện 3 - Đồng Nai'),
(49, 'Huyện 1 - Bà Rịa - Vũng Tàu', 'Huyện 1 - Bà Rịa - Vũng Tàu'),
(49, 'Huyện 2 - Bà Rịa - Vũng Tàu', 'Huyện 2 - Bà Rịa - Vũng Tàu'),
(49, 'Huyện 3 - Bà Rịa - Vũng Tàu', 'Huyện 3 - Bà Rịa - Vũng Tàu'),
(50, 'Huyện 1 - TP. Hồ Chí Minh', 'Huyện 1 - TP. Hồ Chí Minh'),
(50, 'Huyện 2 - TP. Hồ Chí Minh', 'Huyện 2 - TP. Hồ Chí Minh'),
(50, 'Huyện 3 - TP. Hồ Chí Minh', 'Huyện 3 - TP. Hồ Chí Minh'),
(51, 'Huyện 1 - Long An', 'Huyện 1 - Long An'),
(51, 'Huyện 2 - Long An', 'Huyện 2 - Long An'),
(51, 'Huyện 3 - Long An', 'Huyện 3 - Long An'),
(52, 'Huyện 1 - Tiền Giang', 'Huyện 1 - Tiền Giang'),
(52, 'Huyện 2 - Tiền Giang', 'Huyện 2 - Tiền Giang'),
(52, 'Huyện 3 - Tiền Giang', 'Huyện 3 - Tiền Giang'),
(53, 'Huyện 1 - Bến Tre', 'Huyện 1 - Bến Tre'),
(53, 'Huyện 2 - Bến Tre', 'Huyện 2 - Bến Tre'),
(53, 'Huyện 3 - Bến Tre', 'Huyện 3 - Bến Tre'),
(54, 'Huyện 1 - Trà Vinh', 'Huyện 1 - Trà Vinh'),
(54, 'Huyện 2 - Trà Vinh', 'Huyện 2 - Trà Vinh'),
(54, 'Huyện 3 - Trà Vinh', 'Huyện 3 - Trà Vinh'),
(55, 'Huyện 1 - Vĩnh Long', 'Huyện 1 - Vĩnh Long'),
(55, 'Huyện 2 - Vĩnh Long', 'Huyện 2 - Vĩnh Long'),
(55, 'Huyện 3 - Vĩnh Long', 'Huyện 3 - Vĩnh Long'),
(56, 'Huyện 1 - Đồng Tháp', 'Huyện 1 - Đồng Tháp'),
(56, 'Huyện 2 - Đồng Tháp', 'Huyện 2 - Đồng Tháp'),
(56, 'Huyện 3 - Đồng Tháp', 'Huyện 3 - Đồng Tháp'),
(57, 'Huyện 1 - An Giang', 'Huyện 1 - An Giang'),
(57, 'Huyện 2 - An Giang', 'Huyện 2 - An Giang'),
(57, 'Huyện 3 - An Giang', 'Huyện 3 - An Giang'),
(58, 'Huyện 1 - Kiên Giang', 'Huyện 1 - Kiên Giang'),
(58, 'Huyện 2 - Kiên Giang', 'Huyện 2 - Kiên Giang'),
(58, 'Huyện 3 - Kiên Giang', 'Huyện 3 - Kiên Giang'),
(59, 'Huyện 1 - Cần Thơ', 'Huyện 1 - Cần Thơ'),
(59, 'Huyện 2 - Cần Thơ', 'Huyện 2 - Cần Thơ'),
(59, 'Huyện 3 - Cần Thơ', 'Huyện 3 - Cần Thơ'),
(60, 'Huyện 1 - Hậu Giang', 'Huyện 1 - Hậu Giang'),
(60, 'Huyện 2 - Hậu Giang', 'Huyện 2 - Hậu Giang'),
(60, 'Huyện 3 - Hậu Giang', 'Huyện 3 - Hậu Giang'),
(61, 'Huyện 1 - Sóc Trăng', 'Huyện 1 - Sóc Trăng'),
(61, 'Huyện 2 - Sóc Trăng', 'Huyện 2 - Sóc Trăng'),
(61, 'Huyện 3 - Sóc Trăng', 'Huyện 3 - Sóc Trăng'),
(62, 'Huyện 1 - Bạc Liêu', 'Huyện 1 - Bạc Liêu'),
(62, 'Huyện 2 - Bạc Liêu', 'Huyện 2 - Bạc Liêu'),
(62, 'Huyện 3 - Bạc Liêu', 'Huyện 3 - Bạc Liêu'),
(63, 'Huyện 1 - Cà Mau', 'Huyện 1 - Cà Mau'),
(63, 'Huyện 2 - Cà Mau', 'Huyện 2 - Cà Mau'),
(63, 'Huyện 3 - Cà Mau', 'Huyện 3 - Cà Mau');